### ISSUE TITLE
Cannot change width of the pot items inside flex-grow

### ISSUE THREAD

**Issue by bananabrann** [bananabrann/traders-of-the-north#70]
Making this issue as a note to self to go back and fix later. It seems I cannot change the width of the pot items inside the pot, which has flex-grow.

```css
 #pot {
        flex-grow: 10;

        display: flex;
        justify-content: center;
        align-items: center;
        flex-wrap: wrap-reverse;

        > img {
            min-width: none;
            margin: 10px;
        }
    }
```
Am I misunderstanding what flex-grow does? I might need to just revert back to grid.
